version: '3.8'
networks:
  caddy_public:
    
volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - caddy_data:/data
     - caddy_config:/config
     - ./Caddyfile:/etc/caddy/Caddyfile 
    networks:
     - caddy_public
  app:
     build:
        context: .
        dockerfile: Dockerfile
     networks:
        - caddy_public
   


